-- MySQL Script generated by MySQL Workbench
-- Sat Sep 11 02:23:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema finaldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `finaldb` ;

-- -----------------------------------------------------
-- Schema finaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finaldb` DEFAULT CHARACTER SET utf8 ;
USE `finaldb` ;

-- -----------------------------------------------------
-- Table `finaldb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`user` (
                                             `idUser` INT NOT NULL AUTO_INCREMENT,
                                             `NickName` VARCHAR(45) NOT NULL,
                                             `Dateofbirth` VARCHAR(12) NOT NULL,
                                             `Gender` VARCHAR(45) NOT NULL,
                                             `Role` INT NOT NULL,
                                             `Password` VARCHAR(45) NOT NULL,
                                             UNIQUE INDEX `NickName_UNIQUE` (`NickName` ASC) VISIBLE,
                                             PRIMARY KEY (`idUser`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`session` (
                                                `idMovie` INT NOT NULL AUTO_INCREMENT,
                                                `PosterUrl` VARCHAR(45) NOT NULL,
                                                `CountSeat` INT NOT NULL,
                                                `SessionDay` VARCHAR(12) NOT NULL,
                                                `Cost` INT NOT NULL,
                                                `TimeEnd` VARCHAR(45) NOT NULL,
                                                `TimeStart` VARCHAR(45) NOT NULL,
                                                `Status` VARCHAR(45) NOT NULL DEFAULT 'Open',
                                                PRIMARY KEY (`idMovie`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`order` (
                                              `idOrders` INT NOT NULL AUTO_INCREMENT,
                                              `OrderDate` VARCHAR(12) NOT NULL,
                                              `NumberOfSeat` INT NOT NULL,
                                              `user_idUser` INT NOT NULL,
                                              `session_idMovie` INT NOT NULL,
                                              PRIMARY KEY (`idOrders`),
                                              INDEX `fk_order_user1_idx` (`user_idUser` ASC) VISIBLE,
                                              INDEX `fk_order_session1_idx` (`session_idMovie` ASC) VISIBLE,
                                              CONSTRAINT `fk_order_user1`
                                                  FOREIGN KEY (`user_idUser`)
                                                      REFERENCES `finaldb`.`user` (`idUser`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                              CONSTRAINT `fk_order_session1`
                                                  FOREIGN KEY (`session_idMovie`)
                                                      REFERENCES `finaldb`.`session` (`idMovie`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`filmDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`filmDetail` (
                                                   `idfilmDetail` INT NOT NULL AUTO_INCREMENT,
                                                   `Name` VARCHAR(45) NOT NULL DEFAULT 'Cancelled',
                                                   `Description` VARCHAR(1000) NOT NULL DEFAULT 'Cancelled',
                                                   `Actor` VARCHAR(100) NOT NULL DEFAULT 'Cancelled',
                                                   `Director` VARCHAR(100) NOT NULL DEFAULT 'Cancelled',
                                                   `session_idMovie` INT NOT NULL,
                                                   PRIMARY KEY (`idfilmDetail`),
                                                   INDEX `fk_filmDetail_session1_idx` (`session_idMovie` ASC) VISIBLE,
                                                   CONSTRAINT `fk_filmDetail_session1`
                                                       FOREIGN KEY (`session_idMovie`)
                                                           REFERENCES `finaldb`.`session` (`idMovie`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `finaldb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finaldb`.`language` (
                                                 `idLanguage` INT NOT NULL AUTO_INCREMENT,
                                                 `Name` VARCHAR(45) NOT NULL,
                                                 `Description` VARCHAR(45) NOT NULL,
                                                 `filmDetail_idfilmDetail` INT NULL,
                                                 PRIMARY KEY (`idLanguage`),
                                                 INDEX `fk_language_filmDetail1_idx` (`filmDetail_idfilmDetail` ASC) VISIBLE,
                                                 CONSTRAINT `fk_language_filmDetail1`
                                                     FOREIGN KEY (`filmDetail_idfilmDetail`)
                                                         REFERENCES `finaldb`.`filmDetail` (`idfilmDetail`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
